### ISSUE TITLE
System.IO.DirectoryNotFoundException: Downloads folder doesn't exist!

### ISSUE THREAD

**Issue by headcase0570** [MSCLoaderPro/MSCModLoaderPro#24]
New to MSCModLoaderPro.
Issue occurs after MLP detects an available update, shuts itself down and launches CoolUpdater. 
Log attached.

Full message:
**```
(0s) Mod Loader Pro Auto-Update Tool Initialized!

System.IO.DirectoryNotFoundException: Downloads folder doesn't exist!
   bij CoolUpdater.UpdateView.<UpdateAll>d__18.MoveNext()
```**

Updates are not installed. Upon launching MSC, the issue persists and a loop is created.
Paths
Game Folder: D:\Steam\steamapps\common\My Summer Car
Mods Folder: D:\Steam\steamapps\common\My Summer Car\Mods
Save Folder: C:\Users\myusername\AppData\LocalLow\Amistech\My Summer Car

[log.txt](https://github.com/MSCLoaderPro/MSCModLoaderPro/files/6673446/log.txt)

**Comment by ADRIUXX** [comment]
same here....

(0s) Mod Loader Pro Auto-Update Tool Initialized!

System.IO.DirectoryNotFoundException: Downloads folder doesn't exist!
   at CoolUpdater.UpdateView.<UpdateAll>d__18.MoveNext()

**Comment by ChrisChrome** [comment]
Same
(0s) Mod Loader Pro Auto-Update Tool Initialized!

System.IO.DirectoryNotFoundException: Downloads folder doesn't exist!
   at CoolUpdater.UpdateView.<UpdateAll>d__18.MoveNext()
Locations
Game: D:\SteamLibrary\steamapps\common\My Summer Car
Mods: D:\SteamLibrary\steamapps\common\My Summer Car\Mods

**Comment by Tresquel** [comment]
I can't seem to find the updater ever setting a download path.
It's probably somewhere else in the project but I can't seem to find it.

Now to fix it we could create the downloads folder if not found or something else

**Comment by Tresquel** [comment]
I did find it trying to delete the download folder to clean up so the downloads folder is just not getting created

file:
\MSCLoader\CoolUpdater\UpdateView.cs
```cs
// Cleanup after install.
if (!hasFailed)
{
    Directory.Delete(Program.Downloads, true);
    Directory.Delete(Program.Temp, true);
}
```

**Comment by headcase0570** [comment]
I'm not used to GITHUB, it confuses me. Has the issue been solved yet?

**Comment by Tresquel** [comment]
> Has the issue been solved yet?

The issue has not been yet solved but if you need a workaround just create a folder named "Downloads" in ModUpdater in the msc folder

A path to that would look something like this:
"D:\Steam\steamapps\common\My Summer Car\ModUpdater\Downloads"

If you have any other questions lmk

**Comment by Athlon007** [comment]
A bug fix has been integrated and will be present in the next update.
